language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rutgerhofste
  password:
    secure: PGPmw4R7qncWKAckLbeNugJIMORVE/Z1A1qHucYsiHEHSFLZTXXqZRTufU/1/hW0NdlZuaxqFEbN23TDgi7YcWbIz0vWd4Xr223MPLNhL9SJyf8OZKdFOG2iaHgs8PJB+yGq7/U8NACDfiMrr51vv+m1wVklVV5kuF3XgfP3XARh5twGlTbmDekUmgiEofW6VKy8rnXOf9ooVMRoAyYbx92JgNYaOksumwAjHFgd/NcE3FTDNRS1SoLPrc5LXQVJdwspWmKflG4joAx1FILX9/Rkj5twJzKv3h1rIJPN0WUOVUQLAWzJ0KL2p6g8KsqSgh9mRJtvIfdBYlF8IaqTGRShKDev6W2fVKWLROt2oAKjejKFO7JWtwVc2VQWyV8cCZa2aEm+sHUh5S37j3xpOd53Zl0MRV5/V/uvekkjtzj9CdwYdalWPSu6uAiPmaVNY38fpH/o2HvBtMSbSUHOzugbYvIVMZLsa8Lk0OtW5NNgbwuQJL8SuaOxuYnhmrmxrKraxuMv+9ApQkc9Za3Pp25XnrXLCe2JGlynQrdDUmMWb2b1XkbptG8J+25XVY7MHOOOyEV6U+M9dGepzAa+cqX/C77S+q2Mfie7AceenO6gA+MY/MrEMgX3uKYE+gaypesNiRe2YDoBKeKPGXH9IjmhF2mRX2ak5smPOc1rzwM=
  on:
    tags: true
    repo: rutgerhofste/python_package_cookiecutter_template
    python: 3.6
